name: Build Jarvis APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip \
              openjdk-17-jdk unzip libncurses5 build-essential ccache \
              libffi-dev libssl-dev autoconf libtool pkg-config zlib1g-dev \
              libjpeg-dev libpng-dev

          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Rename APK
        run: |
          mkdir -p output
          cp .buildozer/android/platform/build/dists/*/bin/*.apk output/Jarvis.apk || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Jarvis-APK
          path: output/Jarvis.apk
