name: Build Jarvis APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3 python3-pip python3-setuptools
        pip install --upgrade cython buildozer

    - name: Build APK
      run: |
        # Adjust your spec if needed
        sed -i 's/source.main =.*/source.main = jarvis_app.py/' buildozer.spec
        sed -i 's/requirements =.*/requirements = python3,kivy,plyer,gtts,requests,wikipedia/' buildozer.spec
        sed -i 's/android.api =.*/android.api = 33/' buildozer.spec
        sed -i 's/android.minapi =.*/android.minapi = 21/' buildozer.spec
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Jarvis-APK
        path: bin/*.apk
