name: Build Jarvis APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Buildozer
        uses: artem-vladimirov/buildozer-action@v1
        with:
          command: android debug

      - name: Rename APK
        run: |
          mkdir -p output
          cp .buildozer/android/platform/build/dists/*/bin/*.apk output/Jarvis.apk || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Jarvis-APK
          path: output/Jarvis.apk
