name: Build Jarvis APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer (Docker)
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd kivy/buildozer \
          buildozer -v android debug

      - name: Rename APK
        run: |
          mkdir -p output
          mv bin/*.apk output/Jarvis.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Jarvis-APK
          path: output/Jarvis.apk
