name: Build Kivy Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip wget
          pip install buildozer cython virtualenv

      - name: Install Android SDK & accept licenses
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/source.include_exts =.*/source.include_exts = py,mp3,kv,png,jpg,ttf/' buildozer.spec
          sed -i 's/requirements =.*/requirements = python3,kivy,plyer,gtts,requests,wikipedia/' buildozer.spec
          sed -i 's/# *android.api =.*/android.api = 33/' buildozer.spec
          sed -i 's/# *android.minapi =.*/android.minapi = 21/' buildozer.spec
          sed -i 's/# *android.sdk =.*/android.sdk = 33/' buildozer.spec
          sed -i 's/# *android.ndk =.*/android.ndk = 25b/' buildozer.spec
          sed -i 's/source.main =.*/source.main = jarvis_app.py/' buildozer.spec

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JarvisApp
          path: bin/*.apk
